# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /root/developer/projects/mini-debugger

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /root/developer/projects/mini-debugger

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /root/developer/projects/mini-debugger/CMakeFiles /root/developer/projects/mini-debugger/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /root/developer/projects/mini-debugger/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named libelfin

# Build rule for target.
libelfin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libelfin
.PHONY : libelfin

# fast build rule for target.
libelfin/fast:
	$(MAKE) -f CMakeFiles/libelfin.dir/build.make CMakeFiles/libelfin.dir/build
.PHONY : libelfin/fast

#=============================================================================
# Target rules for targets named hello

# Build rule for target.
hello: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hello
.PHONY : hello

# fast build rule for target.
hello/fast:
	$(MAKE) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/build
.PHONY : hello/fast

#=============================================================================
# Target rules for targets named minidbg

# Build rule for target.
minidbg: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 minidbg
.PHONY : minidbg

# fast build rule for target.
minidbg/fast:
	$(MAKE) -f CMakeFiles/minidbg.dir/build.make CMakeFiles/minidbg.dir/build
.PHONY : minidbg/fast

examples/hello.o: examples/hello.cpp.o

.PHONY : examples/hello.o

# target to build an object file
examples/hello.cpp.o:
	$(MAKE) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/examples/hello.cpp.o
.PHONY : examples/hello.cpp.o

examples/hello.i: examples/hello.cpp.i

.PHONY : examples/hello.i

# target to preprocess a source file
examples/hello.cpp.i:
	$(MAKE) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/examples/hello.cpp.i
.PHONY : examples/hello.cpp.i

examples/hello.s: examples/hello.cpp.s

.PHONY : examples/hello.s

# target to generate assembly for a file
examples/hello.cpp.s:
	$(MAKE) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/examples/hello.cpp.s
.PHONY : examples/hello.cpp.s

ext/linenoise/linenoise.o: ext/linenoise/linenoise.c.o

.PHONY : ext/linenoise/linenoise.o

# target to build an object file
ext/linenoise/linenoise.c.o:
	$(MAKE) -f CMakeFiles/minidbg.dir/build.make CMakeFiles/minidbg.dir/ext/linenoise/linenoise.c.o
.PHONY : ext/linenoise/linenoise.c.o

ext/linenoise/linenoise.i: ext/linenoise/linenoise.c.i

.PHONY : ext/linenoise/linenoise.i

# target to preprocess a source file
ext/linenoise/linenoise.c.i:
	$(MAKE) -f CMakeFiles/minidbg.dir/build.make CMakeFiles/minidbg.dir/ext/linenoise/linenoise.c.i
.PHONY : ext/linenoise/linenoise.c.i

ext/linenoise/linenoise.s: ext/linenoise/linenoise.c.s

.PHONY : ext/linenoise/linenoise.s

# target to generate assembly for a file
ext/linenoise/linenoise.c.s:
	$(MAKE) -f CMakeFiles/minidbg.dir/build.make CMakeFiles/minidbg.dir/ext/linenoise/linenoise.c.s
.PHONY : ext/linenoise/linenoise.c.s

src/debugger.o: src/debugger.cpp.o

.PHONY : src/debugger.o

# target to build an object file
src/debugger.cpp.o:
	$(MAKE) -f CMakeFiles/minidbg.dir/build.make CMakeFiles/minidbg.dir/src/debugger.cpp.o
.PHONY : src/debugger.cpp.o

src/debugger.i: src/debugger.cpp.i

.PHONY : src/debugger.i

# target to preprocess a source file
src/debugger.cpp.i:
	$(MAKE) -f CMakeFiles/minidbg.dir/build.make CMakeFiles/minidbg.dir/src/debugger.cpp.i
.PHONY : src/debugger.cpp.i

src/debugger.s: src/debugger.cpp.s

.PHONY : src/debugger.s

# target to generate assembly for a file
src/debugger.cpp.s:
	$(MAKE) -f CMakeFiles/minidbg.dir/build.make CMakeFiles/minidbg.dir/src/debugger.cpp.s
.PHONY : src/debugger.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... libelfin"
	@echo "... hello"
	@echo "... minidbg"
	@echo "... examples/hello.o"
	@echo "... examples/hello.i"
	@echo "... examples/hello.s"
	@echo "... ext/linenoise/linenoise.o"
	@echo "... ext/linenoise/linenoise.i"
	@echo "... ext/linenoise/linenoise.s"
	@echo "... src/debugger.o"
	@echo "... src/debugger.i"
	@echo "... src/debugger.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

